export const TOOGLE_MODAL = 'TOOGLE_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
export const SET_MODAL_STYLE = 'SET_MODAL_STYLE';

export const SHOW_INPUT_LIST = 'SHOW_INPUT_LIST';
export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';

export const SHOW_LOADER = 'SHOW_LOADER';

export const SET_VIDEO_DATA = 'SET_VIDEO_DATA';
export const SET_VIDEO_DATA_PENDING = 'SET_VIDEO_DATA_PENDING';
export const SET_VIDEO_DATA_FULFILLED = 'SET_VIDEO_DATA_FULFILLED';
export const ADD_VIDEO_DATA = 'ADD_VIDEO_DATA';
export const ADD_VIDEO_DATA_PENDING = 'ADD_VIDEO_DATA_PENDING';
export const ADD_VIDEO_DATA_FULFILLED = 'ADD_VIDEO_DATA_FULFILLED';

export const SHOW_ALERT = 'SHOW_ALERT';
export const SET_ALERT = 'SET_ALERT';
export const SET_ALERT_DEFAULT = 'SET_ALERT_DEFAULT';
